firstproject/firstproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('shopping_list/', include('shopping_list.urls')),
    path('spotify_test/', include('spotify_test.urls')),
    path('spotify/', include('spotify.urls')),
]

firstproject/spotify_test/urls.py
from django.urls import path
from . import views

app_name = "spotify_test"

urlpatterns = [
        path('', views.index, name='index'),
        path('auth', views.auth, name='auth'),
        path('logout', views.logout, name='logout'),
        path('index', views.index, name='index'),
        ]

firstproject/todo/urls.py
from django.urls import path
from . import views

app_name = "todo"

urlpatterns = [
        path('', views.index, name='index'),
        path('new_entry', views.new_entry, name="new_entry"),
        path('delete_entry', views.delete_entry, name="delete_entry"),
        ]

firstproject/spotify_test/models.py
from django.db import models

# Create your models here.

firstproject/spotify_test/views.py
from local_credentials import * # imports client_id and client_secret
import os
import spotipy
from django.shortcuts import render

cache_file = './spotify_test/spotify_cache/user'

def index(request):
    logged_in = False

    if os.path.isfile(cache_file):
        logged_in = True

    context = { 'logged_in':logged_in }
    return render(request, 'spotify_test/index.html', context)

def auth(request):
    global cache_file
    redirect_uri = 'http://127.0.0.1:8080'

    if not os.path.exists(os.path.dirname(cache_file)):
        os.makedirs(os.path.dirname(cache_file))

    cache_handler = spotipy.cache_handler.CacheFileHandler(cache_path=cache_file)
    auth_manager = spotipy.oauth2.SpotifyOAuth(client_id=client_id, 
                                               client_secret=client_secret, 
                                               redirect_uri=redirect_uri, 
                                               scope='user-read-recently-played', 
                                               cache_handler=cache_handler, 
                                               show_dialog=True)

    # username = request.POST['username']

    sp = spotipy.Spotify(auth_manager=auth_manager)
    print(sp.current_user_recently_played())
    data = []
    for s in sp.current_user_recently_played()['items']:
        track_name = s['track']['name']
        artist_name = s['track']['album']['artists'][0]['name']
        played_ts = s['played_at']
        print()
        print(f"{track_name} by {artist_name} ({played_ts})")
        data.append({'track':track_name, 'artist': artist_name, 'played_ts': played_ts})

    print(data)

    return render(request, 'spotify_test/auth.html', {'data':data})

def logout(request):
    os.remove(cache_file)
    return render(request, 'spotify_test/index.html')

firstproject/spotify_test/templates/spotify_test/auth.html
{% extends "spotify_test/base.html" %}
{% block content %}

<div class="content">
    <table class="table">
        <tr>
           <th>Track</th>
           <th>Artist</th>
           <th>Time</th>
           <th></th>
        </tr>

        {% for d in data %}
        <tr>
            <td>{{ d.track }}</td>
            <td>{{ d.artist }}</td>
            <td>{{ d.played_ts }}</td>
        </tr>

{% endfor %}

{% endblock %}

firstproject/spotify_test/templates/spotify_test/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Spotify Test App</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    </head>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"> </script>

    <div class="jumbotron jumbotron-fluid" style="text-align:center">
        <h1 class="display-4">Spotify TEST</h1>
        <p class="lead">Testing Spotify Authentification</p>
    <a href='index'><p>HOME</p>
    </a>
    </div>

    <div class="container">
    {% block content %}

    {% endblock %}
    </div>
</body>

</html>

firstproject/spotify_test/templates/spotify_test/index.html
{% extends "spotify_test/base.html" %}
{% block content %}


<div class="content">
    {% if logged_in %}

    <form class="form-row" action="{% url 'spotify_test:auth' %}" method="post">
        {% csrf_token %}    
        <input type="submit" name="login" value="See recently played Songs" class="btn btn-primary">
    </form>
    <br>   
    <form class="form-row" action="{% url 'spotify_test:logout' %}" method="post">
        {% csrf_token %}    
        <input type="submit" name="login" value="Log Out" class="btn btn-primary">
    </form>
    
    {% else %}

    <form class="form-row" action="{% url 'spotify_test:auth' %}" method="post">
        {% csrf_token %}    
        <input type="submit" name="login" value="Login to Spotify" class="btn btn-primary">
    </form>
 {% endif %}
</div>

{% endblock %}