firstproject/firstproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('shopping_list/', include('shopping_list.urls')),
    path('spotify_test/', include('spotify_test.urls')),
    path('spotify/', include('spotify.urls')),
]

firstproject/todo/urls.py
from django.urls import path
from . import views

app_name = "todo"

urlpatterns = [
        path('', views.index, name='index'),
        path('new_entry', views.new_entry, name="new_entry"),
        path('delete_entry', views.delete_entry, name="delete_entry"),
        ]

firstproject/todo/models.py
from django.db import models
from django.utils import timezone

class todo_entry(models.Model):

    todo_text = models.CharField(max_length=200)
    todo_progress = models.BooleanField(default=False)
    todo_date = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.todo_text}"

firstproject/todo/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse

from .models import todo_entry

def index(request):
    latest_todos = todo_entry.objects.order_by('todo_date')
    context = {'latest_todos': latest_todos,}
    return render(request, 'todo/index.html', context)

def new_entry(request):
    todo_entry.objects.create(todo_text=request.POST["new_todo_text"],
                              todo_date=request.POST["new_todo_date"],
                              todo_progress=False)

    return HttpResponseRedirect(reverse('todo:index'))

def delete_entry(request):
    entry = get_object_or_404(todo_entry, id=request.POST["id"])
    entry.delete()
    return HttpResponseRedirect(reverse('todo:index'))

firstproject/todo/templates/todo/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>Todo List</title>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
      </head>
    <body>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"> 
    </script>
        <div class="jumbotron jumbotron-fluid" style="text-align:center">
            <h1 class="display-4">Todo List</h1>
            <p class="lead">A simple way to keep track of things</p>
        </div>

        <div class="container">
           

        <div class="content">
            <table class="table">
                <tr>
                    <th>Due Date</th>
                    <th>Task</th>
                    <th></th>
                </tr>
                
                {% for t in latest_todos %}
                <tr>
                    <td>{{ t.todo_date|date:"Y-m-d" }}</td>
                    <td><b>{{ t.todo_text }}</b></td> 
                    <td>
                    <form style="text-align:right" action="{% url 'todo:delete_entry' %}" method="post" >
                            {% csrf_token %}
                            <input type="hidden" name="id" value ={{ t.id }}>
                            <input type="submit" value="DELETE" class="btn btn-primary">
                    </form>
                    </td>
                </tr>
                {% endfor %}            
            </table>

            <form class="form-row" action="{% url 'todo:new_entry' %}" method="post">
                {% csrf_token %}
                <div class="form-group col-md-5">
                    <input type="text" name="new_todo_text" class="form-control">
                </div>
                <div class="form-group col-md-2">
                    <input type="date" name="new_todo_date" class="form-control">
                </div>
                <div class="form-group col-md-1">
                    <input type="submit" value="ADD" class="btn btn-primary">
                </div>
            </form>
        </div>
        </div>
    </body>
</html>