firstproject/firstproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('shopping_list/', include('shopping_list.urls')),
    path('spotify_test/', include('spotify_test.urls')),
    path('spotify/', include('spotify.urls')),
]

firstproject/shopping_list/urls.py
from django.urls import path
from . import views

app_name = "shopping_list"

urlpatterns = [
        path('', views.index, name='index'),
        path('delete_list' , views.delete_list, name='delete_list'),
        path('delete_shop' , views.delete_shop, name='delete_shop'),
        path('delete_shopping_list_entry' , views.delete_shopping_list_entry, name='delete_shopping_list_entry'),
        path('new_list' , views.new_list, name='new_list'),
        path('new_shop' , views.new_shop, name='new_shop'),
        path('new_list_entry' , views.new_list_entry, name='new_list_entry'),
        path('list/<int:list_id>', views.list, name='list'),
        path('shop/<int:shop_id>', views.shop, name='shop')
        ]

firstproject/todo/urls.py
from django.urls import path
from . import views

app_name = "todo"

urlpatterns = [
        path('', views.index, name='index'),
        path('new_entry', views.new_entry, name="new_entry"),
        path('delete_entry', views.delete_entry, name="delete_entry"),
        ]

firstproject/shopping_list/models.py
from django.db import models

class shopping_list(models.Model):
   shopping_list_name = models.CharField(max_length=200) 

   def __str__(self):
       return f"{self.shopping_list_name}"


class shop_entry(models.Model):
    shop_name = models.CharField(max_length=200)
    shop_open_time = models.CharField(max_length=200)
    
    def __str__(self):
        return f"{self.shop_name}"

class shopping_list_entry(models.Model):
    
    shopping_list_entry_name = models.CharField(max_length=200)
    shopping_list_entry_price = models.FloatField(blank=True)
    shopping_list_entry_amount = models.IntegerField(blank=True)
    shopping_list_entry_done = models.BooleanField(default=False)
    shopping_list_entry_shop = models.ForeignKey(shop_entry, null=True, on_delete=models.SET_NULL)
    shopping_list_entry_list = models.ForeignKey(shopping_list, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.shopping_list_entry_name}"

firstproject/shopping_list/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from . import models

# Create your views here.
def index(request):
    all_lists = models.shopping_list.objects.order_by('shopping_list_name')
    all_shops = models.shop_entry.objects.order_by('shop_name')
    context = { 'all_lists' : all_lists,
                'all_shops' : all_shops, }
    return render(request, 'shopping_list/index.html' , context)

def list(request, list_id):
    all_list_entries = models.shopping_list_entry.objects.filter(shopping_list_entry_list=list_id)
    print(list_id)
    print(all_list_entries)
    all_list_entries.order_by('shopping_list_entry_name')
    context = { 'all_list_entries': all_list_entries,}
    return render(request, 'shopping_list/list.html', context)

def shop(request, shop_id):
    all_shop_entries = models.shopping_list_entry.objects.filter(shopping_list_entry_shop=shop_id)
    context = { 'all_shop_entries': all_shop_entries,}
    return render(request, 'shopping_list/shop.html')

def new_list_entry(request):
    models.shopping_list.objects.create(shopping_list_entry_name=request.POST["new_shopping_list_entry_name"],
                                        shopping_list_entry_amount=request.POST["new_shopping_list_entry_amount"],
                                        shopping_list_entry_price=request.POST["new_shopping_list_entry_price"],
                                        shopping_list_entry_shop=request.POST["new_shopping_list_entry_shop"])
    return HttpResponseRedirect(reverse('shopping_list:index'))

def new_list(request):
    models.shopping_list.objects.create(shopping_list_name=request.POST["new_shopping_list_name"])
    return HttpResponseRedirect(reverse('shopping_list:index'))

def delete_list(request):
    list = get_object_or_404(models.shopping_list, id=request.POST["id"])
    list.delete()
    return HttpResponseRedirect(reverse('shopping_list:index'))

def new_shop(request):
    models.shop_entry.objects.create(shop_name=request.POST["new_shop_name"],
                                     shop_open_time=request.POST["new_shop_open_time"])
    return HttpResponseRedirect(reverse('shopping_list:index'))

def delete_shop(request):
    shop = get_object_or_404(models.shop_entry, id=request.POST["id"])
    shop.delete()
    return HttpResponseRedirect(reverse('shopping_list:index'))

def delete_shopping_list_entry(request):
    shopping_list_entry = get_object_or_404(models.shopping_list_entry, id=request.POST["id"])
    shopping_list_entry.delete()
    return HttpResponseRedirect(reverse('shopping_list:index'))

firstproject/shopping_list/templates/shopping_list/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Shopping List</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

</head>
<body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"> </script>

    <div class="jumbotron jumbotron-fluid" style="text-align:center">
        <h1 class="display-4">Shopping List</h1>
        <p class="lead">A simple way to keep track of things</p>
    </div>

    <div class="container">
    {% block content %}

    {% endblock %}
    </div>
</body>

</html>

firstproject/shopping_list/templates/shopping_list/index.html
{% extends "shopping_list/base.html" %}
{% block content %}

<div class="content">
    <table class="table">
        <tr>
            <th>Liste</th>
            <th></th>
        </tr>

        {% for l in all_lists %}
        <tr>
            <td><a href="{% url 'shopping_list:list' l.id %}"> {{ l.shopping_list_name }}</a></td>
            <td>
                <form style="text-align:right" action="{% url 'shopping_list:delete_list' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value={{ l.id }}>
                    <input type="submit" value="Löschen" class="btn btn-primary">
                </form>
            </td>
        </tr>
        {% endfor %}

    </table>

    <form class="form-row" action="{% url 'shopping_list:new_list' %}" method="post">
        {% csrf_token %}
        <div class="form-group col-md-5">
            <input type="text" name="new_shopping_list_name" class="form-control" placeholder="Neue Liste">
        </div>
        <div class="form-group col-md-1">
            <input type="submit" value="Hinzufügen" class="btn btn-primary">
        </div>
    </form>

</div>

<br></br>

<div class="content">
    <table class="table">
        <tr>
            <th>Laden</th>
            <th>Öffnungszeiten</th>
            <th></th>
        </tr>

        {% for s in all_shops %}
        <tr>
            <td> <a href="{% url 'shopping_list:shop' s.id %}">{{ s.shop_name }}</a></td>
            <td>{{ s.shop_open_time }}</td>
            <td>
                <form style="text-align:right" action="{% url 'shopping_list:delete_shop' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value={{ s.id }}>
                    <input type="submit" value="Löschen" class="btn btn-primary">
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>

    <form class="form-row" action="{% url 'shopping_list:new_shop' %}" method="post">
        {% csrf_token %}
        <div class="form-group col-md-5">
            <input type="text" name="new_shop_name" class="form-control" placeholder="Neuer Shop">
        </div>
        <div class="form-group col-md-5">
            <input type="text" name="new_shop_open_time" class="form-control" placeholder="Öffnungszeit">
        </div>
        <div class="form-group col-md-1">
            <input type="submit" value="Hinzufügen" class="btn btn-primary">
        </div>
    </form>
</div>

{% endblock %}

firstproject/shopping_list/templates/shopping_list/list.html
{% extends "shopping_list/base.html" %}
{% block content %}

<div class="content">
    <table class="table">
        <tr>
           <th>Eintrag</th>
           <th>Menge</th>
           <th>Preis</th>
           <th>Shop</th>
           <th></th>
        </tr>

        {% for e in all_list_entries %}
        <tr>
            <td>{{ e.shopping_list_entry_name }}</td>
            <td>{{ e.shopping_list_entry_amount }}</td>
            <td>{{ e.shopping_list_entry_price }}</td>
            <td>{{ e.shopping_list_entry_shop }}</td>
            <td>
                <form style="text-align:right" action="{% url 'shopping_list:delete_shopping_list_entry' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="id" value={{ s.id }}>
                    <input type="submit" value="Löschen" class="btn btn-primary">
                </form>
            </td>
        </tr>

{% endfor %}

      </table>

      <form class="form-row" action="{% url 'shopping_list:new_list_entry' %}" method="post">
    {% csrf_token %}
    <div class="form-group col-md-5">
        <input type="text" name="new_shopping_list_entry_name" class="form-control" placeholder="Neuer Eintrag">
    </div>
    <div class="form-group col-md-2">
        <input type="int" name="new_shopping_list_entry_amount" class="form-control" placeholder="Menge">
    </div>
    <div class="form-group col-md-2">
        <input type="int" name="new_shopping_list_entry_price" class="form-control" placeholder="Preis">
    </div>
    <div class="form-group col-md-2">
        <input type="text" name="new_shopping_list_entry_shop" class="form-control" placeholder="Shop">
    </div>
    <div class="form-group col-md-1">
        <input type="submit" value="Hinzufügen" class="btn btn-primary">
    </div>
</form>
</div>

{% endblock %}

firstproject/shopping_list/templates/shopping_list/shop.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>Shop</title>
        link
    </head>
    <body>
        body
    </body>
</html>