tutorial/polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

tutorial/tutorial/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

tutorial/polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateField('date published')

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

tutorial/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.http import Http404, HttpResponse

from .models import Question

def index(request):
     latest_question_list = Question.objects.order_by('-pub_date')[:5]
     context = { 'latest_question_list': latest_question_list,}
     return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request,question_id):
    return HttpResponse("You're voting on question %s." % question_id)

tutorial/polls/templates/polls/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <title>{{title}}</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="description" content="" />
</head>
<body>
    <h1>{{title}}</h1>
    <div class="menu">
        <ul>
            <li>Seite 1</li>
            <li>Seite 2</li>
        </ul>
    </div>
    <div class="content">
        {%block content%}
            Leer...sollte nicht erreicht werden!
        {% endblock %}
    </div> 
</body>
</html>

tutorial/polls/templates/polls/begruessung.html
<!DOCTYPE html>

<html lang="en">
<head>
    <title>{{name}}</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="description" content="" />
</head>
<body>
    <h1>Hello, {{name}}!</h1>
</body>
</html>

tutorial/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Details</title>
  </head>
  <body>
  <div class="content">
    <h1>{{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
    {% endfor %}
    </ul>
  </div>
  </body>
</html>

tutorial/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
  </head>
  <body>
  <div class="content">
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
        <p>No polls are available.</p>
        {% endif %}
    </div>
  </body>
</html>